"""init db222

Revision ID: ea218efae69c
Revises: 3d47e95c1aaf
Create Date: 2024-09-03 22:32:24.319590

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "ea218efae69c"
down_revision: Union[str, None] = "3d47e95c1aaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
