/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
/**
 * Enum class CredentialType.
 * @enum {}
 * @readonly
 */
export default class CredentialType {
  /**
   * value: "api_key"
   * @const
   */
  api_key = "api_key";

  /**
   * value: "github_pat"
   * @const
   */
  github_pat = "github_pat";

  /**
   * value: "gcp_service_account"
   * @const
   */
  gcp_service_account = "gcp_service_account";

  /**
   * value: "other"
   * @const
   */
  other = "other";

  /**
   * Returns a <code>CredentialType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/CredentialType} The enum <code>CredentialType</code> value.
   */
  static constructFromObject(object) {
    return object;
  }
}
