/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import CredentialType from "./CredentialType";

/**
 * The CredentialCreate model module.
 * @module model/CredentialCreate
 * @version 0.1.0
 */
class CredentialCreate {
  /**
   * Constructs a new <code>CredentialCreate</code>.
   * @alias module:model/CredentialCreate
   * @param name {String}
   * @param credentialType {module:model/CredentialType}
   * @param data {Object}
   */
  constructor(name, credentialType, data) {
    CredentialCreate.initialize(this, name, credentialType, data);
  }

  /**
   * Initializes the fields of this object.
   * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
   * Only for internal use.
   */
  static initialize(obj, name, credentialType, data) {
    obj["name"] = name;
    obj["credential_type"] = credentialType;
    obj["data"] = data;
  }

  /**
   * Constructs a <code>CredentialCreate</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CredentialCreate} obj Optional instance to populate.
   * @return {module:model/CredentialCreate} The populated <code>CredentialCreate</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CredentialCreate();

      if (data.hasOwnProperty("name")) {
        obj["name"] = ApiClient.convertToType(data["name"], "String");
      }
      if (data.hasOwnProperty("credential_type")) {
        obj["credential_type"] = CredentialType.constructFromObject(
          data["credential_type"],
        );
      }
      if (data.hasOwnProperty("metadata")) {
        obj["metadata"] = ApiClient.convertToType(data["metadata"], Object);
      }
      if (data.hasOwnProperty("data")) {
        obj["data"] = ApiClient.convertToType(data["data"], Object);
      }
    }
    return obj;
  }

  /**
   * Validates the JSON data with respect to <code>CredentialCreate</code>.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CredentialCreate</code>.
   */
  static validateJSON(data) {
    // check to make sure all required properties are present in the JSON string
    for (const property of CredentialCreate.RequiredProperties) {
      if (!data.hasOwnProperty(property)) {
        throw new Error(
          "The required field `" +
            property +
            "` is not found in the JSON data: " +
            JSON.stringify(data),
        );
      }
    }
    // ensure the json data is a string
    if (
      data["name"] &&
      !(typeof data["name"] === "string" || data["name"] instanceof String)
    ) {
      throw new Error(
        "Expected the field `name` to be a primitive type in the JSON string but got " +
          data["name"],
      );
    }

    return true;
  }
}

CredentialCreate.RequiredProperties = ["name", "credential_type", "data"];

/**
 * @member {String} name
 */
CredentialCreate.prototype["name"] = undefined;

/**
 * @member {module:model/CredentialType} credential_type
 */
CredentialCreate.prototype["credential_type"] = undefined;

/**
 * @member {Object} metadata
 */
CredentialCreate.prototype["metadata"] = undefined;

/**
 * @member {Object} data
 */
CredentialCreate.prototype["data"] = undefined;

export default CredentialCreate;
