apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/rad-containers-hmed/ai-platform/api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            # limits:
            #   memory: "1.5Gi"
            #   cpu: "750m"
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: postgres-server
                  key: API_POSTGRES_SERVER
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-user
                  key: API_POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: API_POSTGRES_PASSWORD
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: API_GOOGLE_CLIENT_ID
            - name: CREDENTIAL_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: credential-encryption-key
                  key: API_CREDENTIAL_ENCRYPTION_KEY
            - name: POSTGRES_DB
              value: neondb
            - name: HONEYCOMB_DATASET
              value: dev
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: honeycomb-api-key
                  key: API_HONEYCOMB_API_KEY
            - name: OTEL_SERVICE_NAME
              value: api
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: otel-exporter-otlp-headers
                  key: API_OTEL_EXPORTER_OTLP_HEADERS
      # securityContext:
      #   runAsNonRoot: true
      #   runAsUser: 1000
      # volumes:
      # - name: mysecret
      #   csi:
      #     driver: secrets-store-gke.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: secret-manager
