apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: us-central1-docker.pkg.dev/rad-containers-hmed/ai-platform/api:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1.5Gi"
              cpu: "750m"
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: POSTGRES_SERVER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: POSTGRES_SERVER
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: neondb
            - name: HONEYCOMB_DATASET
              value: dev
            - name: HONEYCOMB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: HONEYCOMB_API_KEY
            - name: GOOGLE_CLIENT_ID
              value: 368747471698-m570pnvdpes6cncrupq9r2vvjp20951m.apps.googleusercontent.com
            - name: CREDENTIAL_ENCRYPTION_KEY
              value: aD7Qdt5ZV4x4PLZdms22PTCAy4CW0Vq8ka-3p_9mXiU=
            - name: OTEL_SERVICE_NAME
              value: api
            - name: OTEL_EXPORTER_OTLP_HEADERS
              value: x-honeycomb-team=1vS8424tiEnmZfDEZiQgLH
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      # volumes:
      # - name: mysecret
      #   csi:
      #     driver: secrets-store-gke.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: secret-manager
