apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: platform-api@rad-dev-platapi-4r64.iam.gserviceaccount.com
automountServiceAccountToken: true
