# pretty cool feature that's almost there, replaces the need for external secret manager
# use this when it supports syncing and k8s secret
# this only writes to file and  it's too annoying to write a script to source them as env vars at the moment
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: secret-manager
# spec:
#   provider: gke
#   parameters:
#     secrets: |
#       - resourceName: "projects/rad-dev-platapi-4r64/secrets/POSTGRES_SERVER/versions/latest"
#         path: "/POSTGRES_SERVER.txt"
