/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChatCreate model module.
 * @module model/ChatCreate
 * @version 0.1.0
 */
class ChatCreate {
    /**
     * Constructs a new <code>ChatCreate</code>.
     * @alias module:model/ChatCreate
     * @param name {String}
     * @param model {String}
     */
    constructor(name, model) {

        ChatCreate.initialize(this, name, model);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, model) {
        obj['name'] = name;
        obj['model'] = model;
    }

    /**
     * Constructs a <code>ChatCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChatCreate} obj Optional instance to populate.
     * @return {module:model/ChatCreate} The populated <code>ChatCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChatCreate();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('is_user_default')) {
                obj['is_user_default'] = ApiClient.convertToType(data['is_user_default'], 'Boolean');
            }
            if (data.hasOwnProperty('is_starred')) {
                obj['is_starred'] = ApiClient.convertToType(data['is_starred'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChatCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChatCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChatCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }

        return true;
    }


}

ChatCreate.RequiredProperties = ["name", "model"];

/**
 * @member {String} name
 */
ChatCreate.prototype['name'] = undefined;

/**
 * @member {String} model
 */
ChatCreate.prototype['model'] = undefined;

/**
 * @member {Boolean} is_user_default
 * @default false
 */
ChatCreate.prototype['is_user_default'] = false;

/**
 * @member {Boolean} is_starred
 * @default false
 */
ChatCreate.prototype['is_starred'] = false;






export default ChatCreate;
