/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChatMessageUpdate model module.
 * @module model/ChatMessageUpdate
 * @version 0.1.0
 */
class ChatMessageUpdate {
    /**
     * Constructs a new <code>ChatMessageUpdate</code>.
     * @alias module:model/ChatMessageUpdate
     */
    constructor() {

        ChatMessageUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) {
    }

    /**
     * Constructs a <code>ChatMessageUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChatMessageUpdate} obj Optional instance to populate.
     * @return {module:model/ChatMessageUpdate} The populated <code>ChatMessageUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChatMessageUpdate();

            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('is_context_file')) {
                obj['is_context_file'] = ApiClient.convertToType(data['is_context_file'], 'Boolean');
            }
            if (data.hasOwnProperty('model')) {
                obj['model'] = ApiClient.convertToType(data['model'], 'String');
            }
            if (data.hasOwnProperty('tokens')) {
                obj['tokens'] = ApiClient.convertToType(data['tokens'], 'Number');
            }
            if (data.hasOwnProperty('content_raw')) {
                obj['content_raw'] = ApiClient.convertToType(data['content_raw'], Object);
            }
            if (data.hasOwnProperty('is_tool_message')) {
                obj['is_tool_message'] = ApiClient.convertToType(data['is_tool_message'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChatMessageUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChatMessageUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['content'] && !(typeof data['content'] === 'string' || data['content'] instanceof String)) {
            throw new Error("Expected the field `content` to be a primitive type in the JSON string but got " + data['content']);
        }
        // ensure the json data is a string
        if (data['model'] && !(typeof data['model'] === 'string' || data['model'] instanceof String)) {
            throw new Error("Expected the field `model` to be a primitive type in the JSON string but got " + data['model']);
        }

        return true;
    }


}



/**
 * @member {String} role
 */
ChatMessageUpdate.prototype['role'] = undefined;

/**
 * @member {String} content
 */
ChatMessageUpdate.prototype['content'] = undefined;

/**
 * @member {Boolean} is_context_file
 */
ChatMessageUpdate.prototype['is_context_file'] = undefined;

/**
 * @member {String} model
 */
ChatMessageUpdate.prototype['model'] = undefined;

/**
 * @member {Number} tokens
 */
ChatMessageUpdate.prototype['tokens'] = undefined;

/**
 * @member {Object} content_raw
 */
ChatMessageUpdate.prototype['content_raw'] = undefined;

/**
 * @member {Boolean} is_tool_message
 */
ChatMessageUpdate.prototype['is_tool_message'] = undefined;






export default ChatMessageUpdate;
