/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlatformApi);
  }
}(this, function(expect, PlatformApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlatformApi.MessagesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesApi', function() {
    describe('deleteChatMessageAdaV1MessagesMessageIdDelete', function() {
      it('should call deleteChatMessageAdaV1MessagesMessageIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteChatMessageAdaV1MessagesMessageIdDelete
        //instance.deleteChatMessageAdaV1MessagesMessageIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('promptAdaV1MessagesPromptPost', function() {
      it('should call promptAdaV1MessagesPromptPost successfully', function(done) {
        //uncomment below and update the code to test promptAdaV1MessagesPromptPost
        //instance.promptAdaV1MessagesPromptPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateChatMessageAdaV1MessagesMessageIdPut', function() {
      it('should call updateChatMessageAdaV1MessagesMessageIdPut successfully', function(done) {
        //uncomment below and update the code to test updateChatMessageAdaV1MessagesMessageIdPut
        //instance.updateChatMessageAdaV1MessagesMessageIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
