/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlatformApi);
  }
}(this, function(expect, PlatformApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlatformApi.ProjectsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectsApi', function() {
    describe('createAdaV1ProjectsPost', function() {
      it('should call createAdaV1ProjectsPost successfully', function(done) {
        //uncomment below and update the code to test createAdaV1ProjectsPost
        //instance.createAdaV1ProjectsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createChatAdaV1ProjectsProjectIdChatsPost', function() {
      it('should call createChatAdaV1ProjectsProjectIdChatsPost successfully', function(done) {
        //uncomment below and update the code to test createChatAdaV1ProjectsProjectIdChatsPost
        //instance.createChatAdaV1ProjectsProjectIdChatsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesPost', function() {
      it('should call createChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesPost successfully', function(done) {
        //uncomment below and update the code to test createChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesPost
        //instance.createChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChatAdaV1ProjectsProjectIdChatsChatIdDelete', function() {
      it('should call deleteChatAdaV1ProjectsProjectIdChatsChatIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteChatAdaV1ProjectsProjectIdChatsChatIdDelete
        //instance.deleteChatAdaV1ProjectsProjectIdChatsChatIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdDelete', function() {
      it('should call deleteChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdDelete
        //instance.deleteChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listProjectsAdaV1ProjectsGet', function() {
      it('should call listProjectsAdaV1ProjectsGet successfully', function(done) {
        //uncomment below and update the code to test listProjectsAdaV1ProjectsGet
        //instance.listProjectsAdaV1ProjectsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readChatAdaV1ProjectsProjectIdChatsChatIdGet', function() {
      it('should call readChatAdaV1ProjectsProjectIdChatsChatIdGet successfully', function(done) {
        //uncomment below and update the code to test readChatAdaV1ProjectsProjectIdChatsChatIdGet
        //instance.readChatAdaV1ProjectsProjectIdChatsChatIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readChatMessagesAdaV1ProjectsProjectIdChatsChatIdMessagesGet', function() {
      it('should call readChatMessagesAdaV1ProjectsProjectIdChatsChatIdMessagesGet successfully', function(done) {
        //uncomment below and update the code to test readChatMessagesAdaV1ProjectsProjectIdChatsChatIdMessagesGet
        //instance.readChatMessagesAdaV1ProjectsProjectIdChatsChatIdMessagesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('readChatsAdaV1ProjectsProjectIdChatsGet', function() {
      it('should call readChatsAdaV1ProjectsProjectIdChatsGet successfully', function(done) {
        //uncomment below and update the code to test readChatsAdaV1ProjectsProjectIdChatsGet
        //instance.readChatsAdaV1ProjectsProjectIdChatsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateChatAdaV1ProjectsProjectIdChatsChatIdPut', function() {
      it('should call updateChatAdaV1ProjectsProjectIdChatsChatIdPut successfully', function(done) {
        //uncomment below and update the code to test updateChatAdaV1ProjectsProjectIdChatsChatIdPut
        //instance.updateChatAdaV1ProjectsProjectIdChatsChatIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdPut', function() {
      it('should call updateChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdPut successfully', function(done) {
        //uncomment below and update the code to test updateChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdPut
        //instance.updateChatMessageAdaV1ProjectsProjectIdChatsChatIdMessagesMessageIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
