/**
 * Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PlatformApi);
  }
}(this, function(expect, PlatformApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PlatformApi.ApiAdaV1EndpointsChatMessagesPostQuery();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ApiAdaV1EndpointsChatMessagesPostQuery', function() {
    it('should create an instance of ApiAdaV1EndpointsChatMessagesPostQuery', function() {
      // uncomment below and update the code to test ApiAdaV1EndpointsChatMessagesPostQuery
      //var instance = new PlatformApi.ApiAdaV1EndpointsChatMessagesPostQuery();
      //expect(instance).to.be.a(PlatformApi.ApiAdaV1EndpointsChatMessagesPostQuery);
    });

    it('should have the property prompt (base name: "prompt")', function() {
      // uncomment below and update the code to test the property prompt
      //var instance = new PlatformApi.ApiAdaV1EndpointsChatMessagesPostQuery();
      //expect(instance).to.be();
    });

    it('should have the property projectId (base name: "projectId")', function() {
      // uncomment below and update the code to test the property projectId
      //var instance = new PlatformApi.ApiAdaV1EndpointsChatMessagesPostQuery();
      //expect(instance).to.be();
    });

  });

}));
