apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
        app: ubuntu
  template:
      metadata:
        labels:
            app: ubuntu
      spec:
        containers:
            - name: ubuntu
              image: ubuntu:latest
              imagePullPolicy: Always
              args: ["tail", "-f", "/dev/null"]
