/*
Platform API

Testing CredentialsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_CredentialsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CredentialsAPIService CreateCredentialAdaV1CredentialsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CredentialsAPI.CreateCredentialAdaV1CredentialsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsAPIService DeleteCredentialAdaV1CredentialsCredentialIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialId int32

		resp, httpRes, err := apiClient.CredentialsAPI.DeleteCredentialAdaV1CredentialsCredentialIdDelete(context.Background(), credentialId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsAPIService ReadCredentialAdaV1CredentialsCredentialIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialId int32

		resp, httpRes, err := apiClient.CredentialsAPI.ReadCredentialAdaV1CredentialsCredentialIdGet(context.Background(), credentialId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsAPIService ReadCredentialsAdaV1CredentialsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.CredentialsAPI.ReadCredentialsAdaV1CredentialsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test CredentialsAPIService UpdateCredentialAdaV1CredentialsCredentialIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var credentialId int32

		resp, httpRes, err := apiClient.CredentialsAPI.UpdateCredentialAdaV1CredentialsCredentialIdPut(context.Background(), credentialId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
