/*
Platform API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// CredentialType the model 'CredentialType'
type CredentialType string

// List of CredentialType
const (
	API_KEY CredentialType = "api_key"
	GITHUB_PAT CredentialType = "github_pat"
	GCP_SERVICE_ACCOUNT CredentialType = "gcp_service_account"
	OTHER CredentialType = "other"
)

// All allowed values of CredentialType enum
var AllowedCredentialTypeEnumValues = []CredentialType{
	"api_key",
	"github_pat",
	"gcp_service_account",
	"other",
}

func (v *CredentialType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CredentialType(value)
	for _, existing := range AllowedCredentialTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CredentialType", value)
}

// NewCredentialTypeFromValue returns a pointer to a valid CredentialType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCredentialTypeFromValue(v string) (*CredentialType, error) {
	ev := CredentialType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CredentialType: valid values are %v", v, AllowedCredentialTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CredentialType) IsValid() bool {
	for _, existing := range AllowedCredentialTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CredentialType value
func (v CredentialType) Ptr() *CredentialType {
	return &v
}

type NullableCredentialType struct {
	value *CredentialType
	isSet bool
}

func (v NullableCredentialType) Get() *CredentialType {
	return v.value
}

func (v *NullableCredentialType) Set(val *CredentialType) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialType) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialType(val *CredentialType) *NullableCredentialType {
	return &NullableCredentialType{value: val, isSet: true}
}

func (v NullableCredentialType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
