/*
Platform API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CredentialCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CredentialCreate{}

// CredentialCreate struct for CredentialCreate
type CredentialCreate struct {
	Name string `json:"name"`
	CredentialType CredentialType `json:"credential_type"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Data map[string]interface{} `json:"data"`
}

type _CredentialCreate CredentialCreate

// NewCredentialCreate instantiates a new CredentialCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialCreate(name string, credentialType CredentialType, data map[string]interface{}) *CredentialCreate {
	this := CredentialCreate{}
	this.Name = name
	this.CredentialType = credentialType
	this.Data = data
	return &this
}

// NewCredentialCreateWithDefaults instantiates a new CredentialCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialCreateWithDefaults() *CredentialCreate {
	this := CredentialCreate{}
	return &this
}

// GetName returns the Name field value
func (o *CredentialCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CredentialCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CredentialCreate) SetName(v string) {
	o.Name = v
}

// GetCredentialType returns the CredentialType field value
func (o *CredentialCreate) GetCredentialType() CredentialType {
	if o == nil {
		var ret CredentialType
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *CredentialCreate) GetCredentialTypeOk() (*CredentialType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *CredentialCreate) SetCredentialType(v CredentialType) {
	o.CredentialType = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CredentialCreate) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CredentialCreate) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CredentialCreate) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CredentialCreate) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetData returns the Data field value
func (o *CredentialCreate) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CredentialCreate) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *CredentialCreate) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o CredentialCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CredentialCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["credential_type"] = o.CredentialType
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CredentialCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"credential_type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCredentialCreate := _CredentialCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCredentialCreate)

	if err != nil {
		return err
	}

	*o = CredentialCreate(varCredentialCreate)

	return err
}

type NullableCredentialCreate struct {
	value *CredentialCreate
	isSet bool
}

func (v NullableCredentialCreate) Get() *CredentialCreate {
	return v.value
}

func (v *NullableCredentialCreate) Set(val *CredentialCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialCreate(val *CredentialCreate) *NullableCredentialCreate {
	return &NullableCredentialCreate{value: val, isSet: true}
}

func (v NullableCredentialCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
