repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files

  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: "v3.1.0"
  #   hooks:
  #     - id: prettier
  #       args: ["--write"]
  #       additional_dependencies:
  #         - prettier@3.1.0
  #         - "@prettier/plugin-xml@3.1.1"

  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v8.56.0"
  #   hooks:
  #     - id: eslint
  #       files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@8.56.0
  #         - eslint-config-react-app@7.0.1
  #         - eslint-plugin-import@2.29.1
  #         - eslint-plugin-jsx-a11y@6.8.0
  #         - eslint-plugin-react@7.33.2
  #         - eslint-plugin-react-hooks@4.6.0

  # - repo: https://github.com/pre-commit/mirrors-stylelint
  #   rev: "v15.11.0"
  #   hooks:
  #     - id: stylelint
  #       files: \.(css|scss)$
  #       additional_dependencies:
  #         - stylelint@15.11.0
  #         - stylelint-config-standard@34.0.0
